# Generated by Django 3.0.1 on 2020-03-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckFile',
            fields=[
                ('path', models.CharField(max_length=600, primary_key=True, serialize=False, verbose_name='文件路径')),
                ('stat', models.CharField(default='', max_length=200, verbose_name='文件的属性')),
                ('MD5', models.CharField(default='', max_length=32, verbose_name='文件MD5值')),
                ('ruleType', models.CharField(max_length=64, verbose_name='文件所属规则')),
                ('ruleCheck', models.CharField(max_length=20, verbose_name='文件检查项')),
                ('record', models.CharField(max_length=1, verbose_name='文件记录')),
            ],
            options={
                'verbose_name': '文件属性表',
            },
        ),
        migrations.CreateModel(
            name='InitFile',
            fields=[
                ('path', models.CharField(max_length=600, primary_key=True, serialize=False, verbose_name='文件路径')),
                ('stat', models.CharField(default='', max_length=200, verbose_name='文件的属性')),
                ('MD5', models.CharField(default='', max_length=32, verbose_name='文件MD5值')),
                ('ruleType', models.CharField(max_length=64, verbose_name='文件所属规则')),
                ('ruleCheck', models.CharField(max_length=20, verbose_name='文件检查项')),
                ('record', models.CharField(max_length=1, verbose_name='文件记录')),
            ],
            options={
                'verbose_name': '文件属性表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userid', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='用户ID')),
                ('username', models.CharField(db_index=True, default='', max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户信息表',
            },
        ),
    ]
