# Generated by Django 2.1.8 on 2020-03-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkfile',
            name='time',
            field=models.CharField(default='', max_length=25, verbose_name='检查日期'),
        ),
    ]
