# Generated by Django 2.1.8 on 2020-03-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0003_auto_20200304_0852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckFile',
        ),
    ]
