# Generated by Django 2.1.8 on 2020-03-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0005_checkfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Msg',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logmsg', models.CharField(default='', max_length=32, verbose_name='消息')),
                ('taskid', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '日志消息表',
            },
        ),
        migrations.CreateModel(
            name='Task_Log',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(verbose_name='用户ID')),
                ('taskname', models.CharField(default='', max_length=32, verbose_name='任务名称')),
                ('time', models.CharField(db_index=True, default='', max_length=25, verbose_name='任务时间')),
                ('state', models.CharField(default='', max_length=1, verbose_name='任务状态')),
            ],
            options={
                'verbose_name': '任务日志表',
            },
        ),
    ]
