# Generated by Django 2.1.8 on 2020-03-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0006_log_msg_task_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_log',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
