# Generated by Django 2.1.8 on 2020-03-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0007_task_log_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_msg',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
