# Generated by Django 2.1.8 on 2020-03-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0008_auto_20200306_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDevice',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(default='', max_length=32, verbose_name='设备名')),
                ('deviceIP', models.CharField(default='', max_length=15, verbose_name='设备IP')),
                ('deviceAddress', models.CharField(default='', max_length=32, verbose_name='设备所在地')),
            ],
            options={
                'verbose_name': '子设备表',
            },
        ),
    ]
